In [58]:
# 데이터 출처
# 서울시 지하철 호선별 역별 승하차 인원 정보 데이터:
#  http://data.seoul.go.kr/dataList/OA-12252/S/1/datasetView.do
import pandas as pd
df = pd.read_csv('./data/seoul_subway.csv',encoding = 'cp949')

In [59]:
# 2026년 3월 데이터만 대상으로하기
# df = df[df['사용월'] == 202603]
# march_df = df['사용월'] == 202603
#이렇게 하면 bool값이 나옴
#데이터를 실제로 가져오려면 df[ ]에 넣아야함!!!!!

# df = df[df['사용월'] == 202603]
df = df.loc[df['사용월'] == 202603]

In [60]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [61]:
# 1. 데이터 읽기:
# 승하차 인원 정보 데이터를 불러오고 DataFrame 구조를 확인
# 1.1. 데이터 불러오기
df

,사용월,호선명,지하철역,04시-05시 승차인원,04시-05시 하차인원,05시-06시 승차인원,05시-06시 하차인원,06시-07시 승차인원,06시-07시 하차인원,07시-08시 승차인원,...,23시-24시 하차인원,00시-01시 승차인원,00시-01시 하차인원,01시-02시 승차인원,01시-02시 하차인원,02시-03시 승차인원,02시-03시 하차인원,03시-04시 승차인원,03시-04시 하차인원,작업일자
0,202603,1호선,동대문,727,14,10804,1943,9387,6880,17052,...,10663,1148,3292,1,351,0,0,0,0,20260403
1,202603,1호선,동대문,727,14,10804,1943,9387,6880,17052,...,10663,1148,3292,1,351,0,0,0,0,20260403
2,202603,1호선,동묘앞,168,3,3038,1024,4442,5924,9248,...,5004,125,2222,2,268,0,0,0,0,20260403
3,202603,1호선,동묘앞,168,3,3038,1024,4442,5924,9248,...,5004,125,2222,2,268,0,0,0,0,20260403
4,202603,1호선,서울역,775,44,11465,11233,36857,65118,117965,...,34984,3735,8125,15,227,0,0,0,0,20260403
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1235,202603,중앙선,지평,0,0,0,0,4,0,138,...,0,0,0,0,0,0,0,0,0,20260403
1236,202603,중앙선,팔당,2,0,142,118,469,485,1249,...,185,0,0,0,0,0,0,0,0,20260403
1237,202603,중앙선,팔당,2,0,142,118,469,485,1249,...,185,0,0,0,0,0,0,0,0,20260403
1238,202603,중앙선,회기,887,9,11958,3932,23393,13225,65124,...,30278,911,6342,0,0,0,0,0,0,20260403
1239,202603,중앙선,회기,887,9,11958,3932,23393,13225,65124,...,30278,911,6342,0,0,0,0,0,0,20260403

In [62]:
# 1.2. 데이터 확인하기
df.info

<bound method DataFrame.info of          사용월  호선명 지하철역  04시-05시 승차인원  04시-05시 하차인원  05시-06시 승차인원  \
0     202603  1호선  동대문           727            14         10804
1     202603  1호선  동대문           727            14         10804
2     202603  1호선  동묘앞           168             3          3038
3     202603  1호선  동묘앞           168             3          3038
4     202603  1호선  서울역           775            44         11465
...      ...  ...  ...           ...           ...           ...
1235  202603  중앙선   지평             0             0             0
1236  202603  중앙선   팔당             2             0           142
1237  202603  중앙선   팔당             2             0           142
1238  202603  중앙선   회기           887             9         11958
1239  202603  중앙선   회기           887             9         11958

      05시-06시 하차인원  06시-07시 승차인원  06시-07시 하차인원  07시-08시 승차인원  ...  \
0             1943          9387          6880         17052  ...
1             1943          9387          6880         17052  ...
2             1024          4442          5924          9248  ...
3             1024          4442          5924          9248  ...
4            11233         36857         65118        117965  ...
...            ...           ...           ...           ...  ...
1235             0             4             0           138  ...
1236           118           469           485          1249  ...
1237           118           469           485          1249  ...
1238          3932         23393         13225         65124  ...
1239          3932         23393         13225         65124  ...

      23시-24시 하차인원  00시-01시 승차인원  00시-01시 하차인원  01시-02시 승차인원  01시-02시 하차인원  \
0            10663          1148          3292             1           351
1            10663          1148          3292             1           351
2             5004           125          2222             2           268
3             5004           125          2222             2           268
4            34984          3735          8125            15           227
...            ...           ...           ...           ...           ...
1235             0             0             0             0             0
1236           185             0             0             0             0
1237           185             0             0             0             0
1238         30278           911          6342             0             0
1239         30278           911          6342             0             0

      02시-03시 승차인원  02시-03시 하차인원  03시-04시 승차인원  03시-04시 하차인원      작업일자
0                0             0             0             0  20260403
1                0             0             0             0  20260403
2                0             0             0             0  20260403
3                0             0             0             0  20260403
4                0             0             0             0  20260403
...            ...           ...           ...           ...       ...
1235             0             0             0             0  20260403
1236             0             0             0             0  20260403
1237             0             0             0             0  20260403
1238             0             0             0             0  20260403
1239             0             0             0             0  20260403

[1240 rows x 52 columns]>

In [ ]:
# 2. 데이터 정제: 
# 데이터 확인 후 형 변환 및 이상치 데이터 처리
# 2.1. 2026년 3월 승하차 인원만 추출


# 3. 데이터 시각화:
#  각 변수별로 추가적인 정제 또는 feature engineering 과정을 거치고 시각화를 총해 데이터 특성 파악
# 3.1. 호선 별 이용객 수 출력
# 3.2. 2호선에서 역별 평균 승하차 인원 데이터 추출
# 3.3. 평균 승하차 인원 수 내림차순으로 막대그래프 출력
# 3.4. 특정 호선의 혼잡 정도와 위치좌표 데이터 병합
# (옵션) 3.5. 특정 호선의 혼잡 정도를 지도에 출력

,사용월,호선명,지하철역,04시-05시 승차인원,04시-05시 하차인원,05시-06시 승차인원,05시-06시 하차인원,06시-07시 승차인원,06시-07시 하차인원,07시-08시 승차인원,...,23시-24시 하차인원,00시-01시 승차인원,00시-01시 하차인원,01시-02시 승차인원,01시-02시 하차인원,02시-03시 승차인원,02시-03시 하차인원,03시-04시 승차인원,03시-04시 하차인원,작업일자
0,202603,1호선,동대문,727,14,10804,1943,9387,6880,17052,...,10663,1148,3292,1,351,0,0,0,0,20260403
1,202603,1호선,동대문,727,14,10804,1943,9387,6880,17052,...,10663,1148,3292,1,351,0,0,0,0,20260403
2,202603,1호선,동묘앞,168,3,3038,1024,4442,5924,9248,...,5004,125,2222,2,268,0,0,0,0,20260403
3,202603,1호선,동묘앞,168,3,3038,1024,4442,5924,9248,...,5004,125,2222,2,268,0,0,0,0,20260403
4,202603,1호선,서울역,775,44,11465,11233,36857,65118,117965,...,34984,3735,8125,15,227,0,0,0,0,20260403
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1235,202603,중앙선,지평,0,0,0,0,4,0,138,...,0,0,0,0,0,0,0,0,0,20260403
1236,202603,중앙선,팔당,2,0,142,118,469,485,1249,...,185,0,0,0,0,0,0,0,0,20260403
1237,202603,중앙선,팔당,2,0,142,118,469,485,1249,...,185,0,0,0,0,0,0,0,0,20260403
1238,202603,중앙선,회기,887,9,11958,3932,23393,13225,65124,...,30278,911,6342,0,0,0,0,0,0,20260403
1239,202603,중앙선,회기,887,9,11958,3932,23393,13225,65124,...,30278,911,6342,0,0,0,0,0,0,20260403